import Footer from '../components/Footer';
import InputFile from '../components/InputFile';
import Header from '../components/Header';
import { Container, Form, Button, Row, Col } from 'react-bootstrap';

function Verification() {
    return (
        <div className="App">
          <Header selection="verification" />
        <header className="App-header">
          <h2 className="text-center pt-5 pb-4">Evidence Verification</h2>
          <h4 className="text-center pt-3 pb-2">Check if a report was registered on the Blockchain by Mura</h4>
          <div className="pt-5"></div>

          <Container fluid>
            <Row>
              <Col sm={4} />
              <Col sm={4} className="borderedDiv" >

              <div className="pt-4" />
              <Form>
              <div style={{ height: '20px' }} />
              <Form.Group controlId="formFile" className="mb-3">
              <Form.Label>Select a report generated by Mura</Form.Label>
              <Form.Control type="file" />
              </Form.Group>

              <div style={{ height: '12px' }} />

              <Button className="submitButton" variant="primary" type="submit">
                  Submit
              </Button>
              <div style={{ height: '20px' }} />

              </Form>
            </Col>

            <Col sm={4} />
            </Row>
          </Container>

        </header>
        <Footer />
      </div>
    );
}
export default Verification;